# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DarwinDevrev < Formula
  desc "The missing man pages for Go binaries"
  homepage "https://github.com/SathishKumarHS/devrev-darwin"
  version "1.0.1"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/SathishKumarHS/darwin-devrev/releases/download/v1.0.1/devrev_1.0.3Darwin_arm64.tar.gz"
      sha256 "7393b40cc8de740f09311cc76552bccc1914c34b2e7cac73b700778ac5d8222f"

      def install
        bin.install "darwin-devrev"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SathishKumarHS/darwin-devrev/releases/download/v1.0.1/devrev_1.0.3Darwin_x86_64.tar.gz"
      sha256 "e0d0a03af25b4a77daa0dd90f472cbedbbac604ae74cdb9f0c5351777e419cfd"

      def install
        bin.install "darwin-devrev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SathishKumarHS/darwin-devrev/releases/download/v1.0.1/devrev_1.0.3Linux_arm64.tar.gz"
      sha256 "10179acd92d8dc425fa39094d905c2160e6ff8ad3b61cb59e0a2c028bb308959"

      def install
        bin.install "darwin-devrev"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SathishKumarHS/darwin-devrev/releases/download/v1.0.1/devrev_1.0.3Linux_x86_64.tar.gz"
      sha256 "a817da297f174fe47c99006745d60eb906b9ef51874cc0702104e633b467bec3"

      def install
        bin.install "darwin-devrev"
      end
    end
  end
end
