# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Darwintest < Formula
  desc "The missing man pages for Go binaries"
  homepage "https://github.com/SathishKumarHS/darwin-test"
  version "0.1.7"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/SathishKumarHS/darwintest/releases/download/v0.1.7/darwintest_1.0.1Darwin_arm64.tar.gz"
      sha256 "2578e5306e8031b9833448d82cf54c49b942bf46c824f856f42fc944dbfa5fa7"

      def install
        bin.install "darwintest"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SathishKumarHS/darwintest/releases/download/v0.1.7/darwintest_1.0.1Darwin_x86_64.tar.gz"
      sha256 "9bf55c09bfda368cd9d481242f2f1da9e89ef0b4580ba2410e7b501accd45f4b"

      def install
        bin.install "darwintest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/SathishKumarHS/darwintest/releases/download/v0.1.7/darwintest_1.0.1Linux_x86_64.tar.gz"
      sha256 "4a83d1aeba457aae5fcdf5e8a1aa62cff6d64c36b3d0de2b1e04b30d379ba3a3"

      def install
        bin.install "darwintest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SathishKumarHS/darwintest/releases/download/v0.1.7/darwintest_1.0.1Linux_arm64.tar.gz"
      sha256 "5f2b2add7e4b9040dc9b0487320738a7f6942dc9c7681cf9422ec09f6a623d47"

      def install
        bin.install "darwintest"
      end
    end
  end
end
