# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Darwintest < Formula
  desc "The missing man pages for Go binaries"
  homepage "https://github.com/SathishKumarHS/darwin-test"
  version "0.1.7"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/SathishKumarHS/darwintest/releases/download/v0.1.7/darwintest_1.0.2Darwin_arm64.tar.gz"
      sha256 "4f029ee3ee063cdf528aa37f79100082c81ca242a014d609c3d696ba8cdc54c0"

      def install
        bin.install "darwintest"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SathishKumarHS/darwintest/releases/download/v0.1.7/darwintest_1.0.2Darwin_x86_64.tar.gz"
      sha256 "11061a89ff418e80cb6653ec37575abcba1eae7e55814103ee5b929ebb4965fc"

      def install
        bin.install "darwintest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SathishKumarHS/darwintest/releases/download/v0.1.7/darwintest_1.0.2Linux_arm64.tar.gz"
      sha256 "1344a5829b0709fcb960ea0a2361ee12a4bac56f2677e924156976f26ac28e9a"

      def install
        bin.install "darwintest"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SathishKumarHS/darwintest/releases/download/v0.1.7/darwintest_1.0.2Linux_x86_64.tar.gz"
      sha256 "252fe12fcc494d98473b6e74c706d46e9c1a36e5c54ae848d8e90fed703db71c"

      def install
        bin.install "darwintest"
      end
    end
  end
end
