# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Darwintest < Formula
  desc "The missing man pages for Go binaries"
  homepage "https://github.com/SathishKumarHS/darwin-test"
  version "0.1.6"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/SathishKumarHS/darwintest/releases/download/v0.1.6/darwintest_11Darwin_arm64.tar.gz"
      sha256 "fbed594b5b6b6cc53e0609a74817ebc38972c2dc93f98eae66e19db477ab4217"

      def install
        bin.install "darwintest"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SathishKumarHS/darwintest/releases/download/v0.1.6/darwintest_11Darwin_x86_64.tar.gz"
      sha256 "0e565e006d8e40e4a006f7e7dace1157d84bf55d949b1a98c63deb7e798fdc68"

      def install
        bin.install "darwintest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/SathishKumarHS/darwintest/releases/download/v0.1.6/darwintest_11Linux_x86_64.tar.gz"
      sha256 "f58413046f8c541c5b7a9070f346fc3b930d1bd5ffaaf981dcf5c95990f67fc3"

      def install
        bin.install "darwintest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SathishKumarHS/darwintest/releases/download/v0.1.6/darwintest_11Linux_arm64.tar.gz"
      sha256 "432fd3d6f799d15e13ab904342a9efb7086732de10013d9e3d558cac4dd153fe"

      def install
        bin.install "darwintest"
      end
    end
  end
end
