# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DarwinDevrev < Formula
  desc "The missing man pages for Go binaries"
  homepage "https://github.com/SathishKumarHS/devrev-darwin"
  version "1.0.1"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/SathishKumarHS/darwin-devrev/releases/download/v1.0.1/darwin-devrev_1.0.3Darwin_arm64.tar.gz"
      sha256 "61e0ec7ae7977567a99a35e3ed82bb4d945d16d2d5d131fe7798d6ad5be1e671"

      def install
        bin.install "darwin-devrev"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SathishKumarHS/darwin-devrev/releases/download/v1.0.1/darwin-devrev_1.0.3Darwin_x86_64.tar.gz"
      sha256 "5f7005fd8accffb6e607077be34e11b541fd374add467736b502c841ba176f57"

      def install
        bin.install "darwin-devrev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SathishKumarHS/darwin-devrev/releases/download/v1.0.1/darwin-devrev_1.0.3Linux_arm64.tar.gz"
      sha256 "b2575c71270640f1a7da0e76d4f3fdd8d937db1b8a46c983ffba33c41016062c"

      def install
        bin.install "darwin-devrev"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SathishKumarHS/darwin-devrev/releases/download/v1.0.1/darwin-devrev_1.0.3Linux_x86_64.tar.gz"
      sha256 "7f8e4f96cb52dd5a98c370483adf1dd34e4bb33e7ae08bea640b531027e2a51a"

      def install
        bin.install "darwin-devrev"
      end
    end
  end
end
