# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devrev < Formula
  desc "The missing man pages for Go binaries"
  homepage "https://github.com/SathishKumarHS/devrev"
  version "1.0.1"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/SathishKumarHS/darwin-devrev/releases/download/v1.0.1/devrev_1.0.3Darwin_arm64.tar.gz"
      sha256 "8f940569e8c6b06f0f9e0a1cab846dd7e349039bf697423aa426f81c833b8445"

      def install
        bin.install "devrev"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SathishKumarHS/darwin-devrev/releases/download/v1.0.1/devrev_1.0.3Darwin_x86_64.tar.gz"
      sha256 "1fc932dd8dcacceaa169d98b1b676d700722e109cce45a8c59f2a1851cdae097"

      def install
        bin.install "devrev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SathishKumarHS/darwin-devrev/releases/download/v1.0.1/devrev_1.0.3Linux_arm64.tar.gz"
      sha256 "613bc1dbd16fe61532cb8fad41da3f588b5e5ecd570aac700ea59489050cd689"

      def install
        bin.install "devrev"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SathishKumarHS/darwin-devrev/releases/download/v1.0.1/devrev_1.0.3Linux_x86_64.tar.gz"
      sha256 "4c773495e4cbd9d50bfb927c08cc138db0bb0e91566e86e78abdf1421fba0f5a"

      def install
        bin.install "devrev"
      end
    end
  end
end
