# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devrev < Formula
  desc "devrev-cli"
  homepage "https://devrev.ai"
  version "0.3.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/devrev/brew-devrev-cli/releases/download/v0.3.2/devrev_Darwin_arm64.tar.gz"
      sha256 "1b385d62103ad85a0132d1c50ee7e0203de40777105d7a2352fd17a8c2eebb73"

      def install
        bin.install "devrev"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devrev/brew-devrev-cli/releases/download/v0.3.2/devrev_Darwin_x86_64.tar.gz"
      sha256 "bbd926469a3a845b5562e1e55b2489080ed38359a7cff7d467aee8a09b616cd4"

      def install
        bin.install "devrev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devrev/brew-devrev-cli/releases/download/v0.3.2/devrev_Linux_arm64.tar.gz"
      sha256 "b8c4f257ab379a311664657a860641b4b495e265e8fc154e465210b0c1ffe861"

      def install
        bin.install "devrev"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devrev/brew-devrev-cli/releases/download/v0.3.2/devrev_Linux_x86_64.tar.gz"
      sha256 "4ea87755caa00f9022c49ad542bf46fe90a4da0374e7c50a07f534e981b824c0"

      def install
        bin.install "devrev"
      end
    end
  end
end
