# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devrev < Formula
  desc "The missing man pages for Go binaries"
  homepage "https://github.com/SathishKumarHS/devrev"
  version "1.0.1"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/SathishKumarHS/darwin-devrev/releases/download/v1.0.1/devrev_1.0.3Darwin_arm64.tar.gz"
      sha256 "6f3feda93222e9fb6bd40da9a5081333e4bfb518920482a63ee7c1a4436f95e4"

      def install
        bin.install "devrev"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SathishKumarHS/darwin-devrev/releases/download/v1.0.1/devrev_1.0.3Darwin_x86_64.tar.gz"
      sha256 "974b17c0093fcc6218b21b62c8c40cc505a6721a17bd5753f033074042999037"

      def install
        bin.install "devrev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SathishKumarHS/darwin-devrev/releases/download/v1.0.1/devrev_1.0.3Linux_arm64.tar.gz"
      sha256 "2129835ddc44f650cef6df53bdf0dfcdaaed32485c492a04c868ebcd9b76ae1e"

      def install
        bin.install "devrev"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SathishKumarHS/darwin-devrev/releases/download/v1.0.1/devrev_1.0.3Linux_x86_64.tar.gz"
      sha256 "a3dd95a5853317e7238beea56bf34139ce8dc9f735d1c10b4de28488d265d5f4"

      def install
        bin.install "devrev"
      end
    end
  end
end
